spring:
  application:
    name: user
#  cloud:
#    sentinel:
#      eager: true
#      transport:
#        dashboard: 127.0.0.1:8080
#        port: 8719
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/full?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root

#  security:
#    user:
#      name: root
#      password: root

server:
  port: 8000

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.lmh.user.entity
